---
Rooms:
 - name : Kitchen
   description : This is the kitchen, there is 1 door to the south and to the west.
 - name : Living_room
   description : This is the Living Room, there is a door to the west and a carpet on the floor. It seems like there is something under the carpet. 
 - name : Bedroom
   description : This is the Bedroom, there are a door to the east. 
 - name : Bathroom
   description : This is the Bathroom, there is a door to the east, a door to the west, and north. There is a statue of Aphrodite.
 - name : Pantry
   description : You did it! You found Pikachu!
 - name : Library
   description : This is the Library, there is a door to the east, and a key on the ground.

---
Doors:
 - id : 1
   from_ : east 
   to : west
   state : open
   from_room : Bedroom
   to_room : Bathroom
 - id : 2
   from_ : west
   to : east
   state : open
   from_room : Bathroom
   to_room : Bedroom
 - id : 3
   from_ : north
   to : south
   state : open
   from_room : Bathroom
   to_room : Kithchen
 - id : 4
   from_ : south
   to : north
   state : open
   from_room : Kitchen
   to_room : Bathroom
 - id : 5
   from_ : east
   to : west
   state : closed
   from_room : Bathroom
   to_room : Living_room
 - id : 6
   from_ : west
   to : east
   state : closed
   from_room : Living_room
   to_room : Bathroom
 - id : 7
   from_ : north
   to : south
   state : locked
   from_room : Living_room
   to_room : Pantry
 - id : 8
   from_ : south
   to : north
   state : locked
   from_room : Pantry
   to_room : Living_room
 - id : 9
   from_ : west
   to : east
   state : closed
   from_room : Kitchen
   to_room : Library
 - id : 10
   from_ : east
   to : west
   state : closed
   from_room : Library
   to_room : Kitchen


---
Items:
 - name : key
   description : This is a key to open a door. 
   place: Library
   usage : USE
   action : unlock 
 - name : carpet
   description : This is a carpet. There is something under the carpet. 
   place: Living_room
   usage : MOVE 
   action : None
 - name : statue
   description : A marbel statue of the ancient Greek goddess of Love, Aphrodite. 
   place: Bathroom
   usage : STATIONARY
   action : NONE 
 - name : stone
   description : A shiny stone that has a lightning bolt on it. 
   place: Kitchen
   usage : TAKE
   action : NONE


---

Starting_position:
 - place : Bedroom 




